### ISSUE TITLE
FormatPx.dll Source Code

### ISSUE THREAD

**Issue by lordmilko** [KirkMunro/FormatPx#7]
I see that the source to FormatPx.dll is not included in this repo, and unfortunately decompilers do not appear to do a good job of understanding the binary.

 As including the source directly within the repo would mess up your Install-GitHubHostedModule script, would it potentially be possible to include a zip of the binary's source in a response to this issue, or as an attachment to releases?

Regards,
lordmilko

**Comment by KirkMunro** [comment]
The source code is in the repo. I just did it in a different way. I wanted the master branch to contain the latest version of the module, without throwing C# code into the mix, so I put the dll code on a different branch called assembly. I believe separation of PowerShell code from C# is still useful, but I would set this project up differently if I did it from scratch now, and I still want to evolve it to having all code on the same branch.

Anyhow, go to the assembly branch and you can get all of the source for the dll.

**Comment by lordmilko** [comment]
Awesome! Thanks!
